### ISSUE TITLE
version 1.9.0 breaks "Generic USB Serial" when LTO is enabled

### ISSUE THREAD

**Issue by danyhm** [stm32duino/Arduino_Core_STM32#1076]
**Describe the bug**
After updating to 1.9.0 the Generic USB Serial won't work anymore when compiled with smallest +LTO option.

**To Reproduce**
use the AnalogeReadSerial example

upgrade to 1.9.0

**Expected behavior**
The Serial should work.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Arduino IDE version: [e.g. 1.8.12]
 - STM32 core version: [e.g. 1.9.0]
 - Tools menu settings if not the default: [e.g. Newlib nano, Generic Serial + CDC superseed USART]
 - Upload method: any

**Board (please complete the following information):**
 - Name: [bluepill 64k]

in version 1.8.0 Serial works with LTO option but after updating to 1.9.0 it just doesn't work

**Comment by fpistm** [comment]
LTO is provided "as is", depending of the sketch it works or not. They are several issue linked to the toolchain and LTO.

**Comment by danyhm** [comment]
in 1.8.0 it used to work. so i think some change in 1.9.0 broke it

**Comment by fpistm** [comment]
I know it reduces the size and that's why the option is provided anyway there are other examples like this... I already try to understand why and always end to issue with issue linked to the toolchain.
So I will not spent time to invest on this, it is provided "as it" if it works fine else do not use it.
One other things which does not help is how Arduino handle compiled object and the cache.

**Comment by danyhm** [comment]
![Untitled](https://user-images.githubusercontent.com/21024667/82465056-11c3a480-9ad4-11ea-9c27-2c3a672e5c55.png)
![Untitled2](https://user-images.githubusercontent.com/21024667/82465063-1425fe80-9ad4-11ea-8e84-1bfda4f03ae6.png)
![Untitled3](https://user-images.githubusercontent.com/21024667/82465069-1720ef00-9ad4-11ea-96cd-70fdc9f8d5e6.png)
![Untitled4](https://user-images.githubusercontent.com/21024667/82465078-18eab280-9ad4-11ea-9284-7eb370d55478.png)
![Untitled5](https://user-images.githubusercontent.com/21024667/82465083-1ab47600-9ad4-11ea-83ab-7778299bee5b.png)
in the screenshots above you see the compiler has generated some RTTI(if I'm not mistaken) which won't ever be used by the MCU. and of course, there are some other optimizations. on a single sketch, I get around 20K of flash size optimization while using LTO. if only I knew how to solve it I'd definitely do it.

**Comment by fpistm** [comment]
> if only I knew how to solve it I'd definitely do it

The same. As said I spend lot of time for this and I conclude LTO was not enough mature.
And so will not spend more time on this. Feel free to work on this and provide a "fix", this will be really appreciated, anyway my feeling is it is linked to issue on this feature in the toolchain and/or how arduino manage the build.

**Comment by danyhm** [comment]
@fpistm I'll try my best. right now i reverted to 1.8.0 and it doesn't work again. i think it has something to do with the cache of the compiled object.

**Comment by fpistm** [comment]
Yes, this cache is really not well managed that's why I already need to do some stuff to avoid issue with weaked function for example.... When I get any doubt I always close and restart IDE... and even ensure to delete all cache file in the temp dir. In a previous Arduino IDE we were able to disable it but now not 😢
