### ISSUE TITLE
Menu entry for internal clock?

### ISSUE THREAD

**Issue by mrguen** [stm32duino/Arduino_Core_STM32#1095]
**The problem:**
I am building a barebone STM32F401RCT6 board. Possibly I did not choose an appropriate external clock since the amplitude is half what I can see on the CoreBoard STM32F401RC and with some noise on OSC_OUT pin. I can upload to this board using SWD but USB is not working, so I suspect the clock might be the problem.

**A global improvement request:**

You already worked on this board variant request https://github.com/stm32duino/Arduino_Core_STM32/pull/582 

Maybe it would be convenient to have the possibility to choose an  internal clock "safe" settings from the menu for any board?

**Comment by mrguen** [comment]
Update: from this https://community.st.com/s/question/0D50X00009XkiP7SAJ/master-clock-output-issue , possibly the speed setting of PA8 might be too low?

**Comment by fpistm** [comment]
Hi @mrguen 

I never try the MCO. Those comments were added by @MCUdude.
Looking at the datasheet:
![image](https://user-images.githubusercontent.com/20641798/84504171-c445ec00-acbb-11ea-8868-0864d7e96d76.png)

About the GPIO speed, it is set at the maximum speed for both pins:
https://github.com/stm32duino/Arduino_Core_STM32/blob/9876616ab241e3a041c10d6afc934c1748dda00a/system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c#L783
and:
https://github.com/stm32duino/Arduino_Core_STM32/blob/9876616ab241e3a041c10d6afc934c1748dda00a/system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c#L807
where :
https://github.com/stm32duino/Arduino_Core_STM32/blob/9876616ab241e3a041c10d6afc934c1748dda00a/system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c#L783

I've tested the MCO as you've made (commenting HSE and enabling the MCO outpute) using the generic F411Rx variant and a Nucleo F411RE:
![image](https://user-images.githubusercontent.com/20641798/84511646-1e987a00-acc7-11ea-8c82-d57f303e64bc.png)
And it works as expected (note that I've used a logic analyzer with on a 200MHz resolution, that's why it is not very precise :wink:)

I don't know why it does not work for your core board with PA8 and I could not help on this as the HAL is working as expected, maybe an hardware issue? Wiring issue? ...
About your barebone one, well I could not help you to bring up it. It is your custom board/design and here it is for real issue on the STM32 core. You can ask some help on the forum which is for primary support and there is already some topic about custom boards: https://www.stm32duino.com

Finally the fact you can upload does not means your board is OK, BOOT pins management, NRST, ... 

Some hints:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi50pntu_zpAhXl0eAKHWXIAkYQFjAAegQIARAB&url=https%3A%2F%2Fwww.st.com%2Fresource%2Fen%2Fapplication_note%2Fdm00354244-stm32-microcontroller-debug-toolbox-stmicroelectronics.pdf&usg=AOvVaw3hdppJBJxsRriasyal86JE

**Comment by mrguen** [comment]
@fpistm There is certainly an (first) initilization issue.  

Here is what I tested:

1 ) Simply Uncommenting HAL_RCC_MCOConfig(RCC_MCO1, RCC_MCO1SOURCE_HSI, RCC_MCODIV_1); // 16 MHz
Not working

2) adding the MCO1 activation code in a sketch: working

3) commenting again HAL_RCC_MCOConfig in variant.cpp and commenting HAL_GPIO_Init and MODIFY_REG(RCC->CFGR... in the sketch
Not working - as expected

4) activating the code in the sketch (no activation in variant.cpp): working

5) deactivating into sketch and activating into variant.cpp again
**working**!
