### ISSUE TITLE
nucleo103rb D5 D9 PWM

### ISSUE THREAD

**Issue by MapleHan** [stm32duino/Arduino_Core_STM32#1108]
Why can't PB4（D5） and PC7（D9） output PWM at the same time？Nucleo64 F103RBT6

**Comment by fpistm** [comment]
If you use analogWrite then both pins use the same Timer instance TIM3 (even if not the same channel).
You should use the HardwareTimer instead to be able to use both  on a different channel:
https://github.com/stm32duino/wiki/wiki/HardwareTimer-library

Please for this kind of questions/support use the forum: https://www.stm32duino.com

**Comment by MapleHan** [comment]
Why can't "analogWrite" realize two channel OUTPUT PWM of the same timer, but HardwareTimer can?
Thank you for your reply!

**Comment by fpistm** [comment]
Because t is implemented like this, it simply get the port, get the timer and then configure the TIM instance. No channel management.

**Comment by MapleHan** [comment]
OK, I understand. Thank you

**Comment by MapleHan** [comment]
D5(PB4) and D9(PC7) cannot output PWM by "analogWrite" simultaneously, so why does the nucleo Board choose PB4 and PC7 as D5 and D9? This conflicts with the Arduino habit

**Comment by fpistm** [comment]
This more software restrictions than hardware one.

**Comment by fpistm** [comment]
Hi @MapleHan 
In fact I was wrong on my answer.

Using the same Timer with different channel is ok with analogWrite.
The fact it's not work for those 2 pins is simply because F1 has not the same alternate function management than the other STM32 series.
In your case:
D5 is PB4 with TIM3 channel1 and the AF is AFIO_TIM3_PARTIAL
D9 is PC7 with TIM3 channel 2 and the AF is AFIO_TIM3_ENABLE

Issue is PB4 and PC7 doesn't have the same AFIO.
So it is not possible to have both PWM at the same time and it is a hardware restriction.

If you use PC6 (TIM3 Channel1 but AFIO_TIM3_ENABLE) instead of PB4, this works.

**Comment by MapleHan** [comment]
ok，
I checked the information through your prompt, you are right.
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Frederic Pillon"<notifications@github.com&gt;; 
发送时间: 2020年7月1日(星期三) 晚上8:40
收件人: "stm32duino/Arduino_Core_STM32"<Arduino_Core_STM32@noreply.github.com&gt;; 
抄送: "Maple Leaf"<190258039@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [stm32duino/Arduino_Core_STM32] nucleo103rb D5 D9 PWM (#1108)





 
Hi @MapleHan
 In fact I was wrong on my answer.
 
Using the same Timer with different channel is ok with analogWrite.
 The fact it's not work for those 2 pins is simply because F1 has not the same alternate function management than the other STM32 series.
 In your case:
 D5 is PB4 with TIM3 channel1 and the AF is AFIO_TIM3_PARTIAL
 D9 is PC7 with TIM3 channel 2 and the AF is AFIO_TIM3_ENABLE
 
Issue is PB4 and PC7 doesn't have the same AFIO.
 So it is not possible to have both PWM at the same time and it is a hardware restriction.
 
If you use PC6 (TIM3 Channel1 but AFIO_TIM3_ENABLE) instead of PB4, this works.
