### ISSUE TITLE
Wrong flash size for eeprom emulation

### ISSUE THREAD

**Issue by JyeSmith** [stm32duino/Arduino_Core_STM32#1316]
Hey,

I am trying to use eeprom on the STM32L432.  It should be pretty straight forward but I dont appear to be having any luck.  Is someone able to confirm it works?

Cheers

**Comment by fpistm** [comment]
Hi @JyeSmith 
could you be more precise ?
Which board? Arduino IDE version? Core version ?
Which sketch?

Basically the EEPROM library is an emulation using last page flash.

**Comment by fpistm** [comment]
I've tested `eeprom_put `and `eeprom_get `default examples and it works fine on the Nucleo L432KC

**Comment by cruwaller** [comment]
@fpistm this is not working as expected on L432 when flash size is smaller than max 256kB :)

Current code calculates flash page index:
`#define FLASH_PAGE_NUMBER   ((uint32_t)((FLASH_SIZE / FLASH_PAGE_SIZE) - 1))` 
=> FLASH_SIZE returns 0x20000 and page is 0x800 => page 63 (the address `0x0801F800`). 

Then EEPROM base address is defined:
`#define FLASH_BASE_ADDRESS  ((uint32_t)((FLASH_END + 1) - FLASH_PAGE_SIZE))`
=> `#define FLASH_END             (0x0803FFFFUL)` is defined in `stm32l432xx.h` => `0x0803FFFFUL` => base address will be `0x803F800` which is actually page 127 :)

This means that EEPROM save will work just once after mass erase because wrong flash page is erased :)

Could you reopen this error?

**Comment by fpistm** [comment]
@ABOSTM could you have a look on this please? Thanks in advance.

**Comment by ABOSTM** [comment]
@JyeSmith,
I agree with you, it is a real issue.
FLASH_END which is defined in CMSIS file doesn't take into account the real flash size of a the device,
(it is just the maximum possible within the  productline).

But fix will be a real challenge, as other STM32 series are impacted, and it will be difficult to find generic implementation, taking into account single bank/dual bank, possible flash discontinuity between banks, ...
So as a workaround, I propose you to update, for now, stm32l432xx.h with the value you expected:
`#define FLASH_END (0x0801FFFFUL)`

**Comment by Kamoool** [comment]
I cannot save to EEPROM as well on STM32L432KBU6 on latest version.
On 1.8.0 both EEPROM.put and EEPROM.get worked.
