### ISSUE TITLE
Readme.md should be updated to show support for variant F446ZE

### ISSUE THREAD

**Issue by zouden** [stm32duino/Arduino_Core_STM32#1487]
The readme.md file ([here](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/README.md)) does not list the STM32F446ZE as a supported board. However, 5 months ago this folder was added: 

https://github.com/stm32duino/Arduino_Core_STM32/tree/2.0.0/variants/STM32F4xx/F446Z(C-E)(H-J-T)

I believe this means the F446ZE is supported, but the readme.md file hasn't been updated to show this.

**Comment by fpistm** [comment]
Hi @zouden 
Yes the folder exists because we now generate automatically all the generic variants for all MCU of supported family.
But to enable the support it misses the linker script and a default system clock then it can be declared to the boards.txt.
Goal is to ease boards/MCU support.
You can find more info here:
https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-%28board%29#what-is-a-variant
