### ISSUE TITLE
Ucglib_Arduino

### ISSUE THREAD

**Issue by xmenxwk** [stm32duino/Arduino_Core_STM32#1538]
**Describe the bug**
Unable to compile with Ucglib_Arduino while it says in wiki its tested with ST7735
```
C:\Users\USER\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.0.0\libraries\Ucglib_Arduino-master\src\Ucglib.cpp: In function 'void ucg_com_arduino_send_8bit(ucg_t*, uint8_t)':
C:\Users\USER\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.0.0\libraries\Ucglib_Arduino-master\src\Ucglib.cpp:834:3: error: '__NOP' was not declared in this scope
  834 |   __NOP;
      |   ^~~~~
exit status 1
Error compiling for board Nucleo-144.
```

**To Reproduce**
 ```
#include "Ucglib.h"
Ucglib_ST7735_18x128x160_SWSPI ucg(/*sclk=*/ PB3, /*data=*/ PB5, /*cd=*/ PA6, /*cs=*/ PA5, /*reset=*/ PB12);
```

Wont Compile

**Expected behavior**
Should compile

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Arduino IDE version: 1.6.11
 - STM32 core version: 2.0.0
 - Upload method: Mass Storage

**Board (please complete the following information):**
 - Name: Nucleo H743ZI2

**Comment by fpistm** [comment]
Hi,
this issue is not relevant for the core as `__NOP` is not Arduino standard but linked to arch. 
It is an issue from the library, several issue and PR exists against this:
https://github.com/olikraus/Ucglib_Arduino/issues/22
https://github.com/olikraus/Ucglib_Arduino/issues/5
https://github.com/olikraus/Ucglib_Arduino/pull/6
https://github.com/olikraus/ucglib/pull/149

So simply apply the patch.
