### ISSUE TITLE
exec: "/bin/arm-none-eabi-g++": file does not exist

### ISSUE THREAD

**Issue by ramimehyar** [stm32duino/Arduino_Core_STM32#1622]
I did everything as mentioned and i can get the e5 board, but i get while compiling:

exec: "/bin/arm-none-eabi-g++": file does not exist
Error compiling for board Generic STM32WL series.

Please help me get past this.

**Comment by fpistm** [comment]
Could you be more precise? Which core version, IDE version? Selected options in the menu? ....
All relevant information would help to solve your issuel.  And what is the e5 board?

**Comment by ramimehyar** [comment]
in the wiki of bertrik, he says to create the directory using the option -f which is not recognized by my gitbash.

like this:   mkdir -f stm32

so I do create the stm32 dir without -f option.

**Comment by ramimehyar** [comment]
And when i try to execute: 
$ git checkout seeed_lora_e5_mini

I get:
User@DESKTOP-63Q81U9 MINGW64 /c/Program Files (x86)/Arduino/hardware/stm32
$ git checkout seeed_lora_e5_mini
fatal: not a git repository (or any of the parent directories): .git

**Comment by ramimehyar** [comment]
Please help me, i am not able to add the fork

**Comment by fpistm** [comment]
So as stated in your other issue you try to follow instructions outside of this organisation. Therefore you should ask support to bertrik.

**Comment by fpistm** [comment]
For ref: https://revspace.nl/LoRa-E5-mini

As his fork is not up to date then there is a misalignment with the installed tool (here the arm none eabi gcc). 
You have installed the latest core version 2.2.0 which install the arm-none-eabi-gcc 10.3.1-2.3   while his fork is based on previous version 10.2.1-1.1. That's why you get this error. Simply install  the 2.1.0 instead of the 2.2.0 and it should works.

But as stated if you met another issue please raise an issue on bertrik GH: https://github.com/bertrik/Arduino_Core_STM32/

**Comment by ramimehyar** [comment]
Many thanks, you really helped me! I understand, if i had issues ill ask
him there.

Regards,
