### ISSUE TITLE
Difference between two consecutive micros() can be negative if interrupts are disabled.

### ISSUE THREAD

**Issue by ArminJo** [stm32duino/Arduino_Core_STM32#2087]
### Describe the bug
It is like #1680, and the current implementation still has this problem described by [matthijskooijman](https://github.com/matthijskooijman):

```
uint32_t getCurrentMicros(void)
{
  uint32_t m0 = HAL_GetTick();
  __IO uint32_t u0 = SysTick->VAL;
  uint32_t m1 = HAL_GetTick();
  __IO uint32_t u1 = SysTick->VAL;
  const uint32_t tms = SysTick->LOAD + 1;

  if (m1 != m0) {
    return (m1 * 1000 + ((tms - u1) * 1000) / tms);
  } else {
    return (m0 * 1000 + ((tms - u0) * 1000) / tms);
  }
}
```
### To Reproduce
This error leads to https://github.com/Arduino-IRremote/Arduino-IRremote/issues/1152, which can easily reproduced by compiling the SendDemo example of IRRemote library version 4.1.0. After a few seconds, IR output signal generation stops (as expected since I analyzed this bug 😞 ).
Deactivating the disable of the interrupt statement `noInterrupts();` in IRSend.hpp near line 1044 fixes the error.

### Expected behavior
When calling micros() twice, the second call should always return equal or more than the first call.

### Solutions
I have no idea for an solution, but it should at least be documented in the code, to avoid long investigations.

**Comment by fpistm** [comment]
Hi @ArminJo 
`micros()` relies on systick interrupt. If you disable the interrupt, systick is no more incremented.
If you really need to disable interrupt you can try to use `delayMicrosecond` which uses DWT free running counter, so instead of compute time manually simply wait the request time.
Or as you do do not disable interrupt.

The point you mention from @matthijskooijman is not the same than here.So, unfortunately, I can't do nothing for your issue as if you disable interrupt you freeze the tick.
