### ISSUE TITLE
can't compile on macOS

### ISSUE THREAD

**Issue by sstaub** [stm32duino/Arduino_Core_STM32#233]
STM32 version 1.2.0, MacBook Pro 15''(2011), 10.13.4, Arduin 1.8.5
Compiling on macOS is not posible, the Arduino IDE doesn't find the board

Following Error:
Arduino: 1.8.5 (Mac OS X), TD: 1.40, Board: "Nucleo-32, Nucleo F303K8, Mass Storage, Generic Serial, None, Smallest (-Os default)"
Board Nucleo_32 (Plattform stm32, Paket STM32) ist unbekannt (is unknown)

On Win10 on the same computer with parallel desktop, it works

**Comment by fpistm** [comment]
Hi @sstaub 
This is due to this:
Release versioning has been changed from date versioning to semantic one. See [Release Versioning change](https://github.com/stm32duino/wiki/wiki/Release-Versioning-change)

**Comment by sstaub** [comment]
Here the screenshot of the board manager, version of the core is 1.2.0
<img width="786" alt="screenshot" src="https://user-images.githubusercontent.com/6450325/38140358-aaaa9276-3433-11e8-80f7-42bb0943268e.png">

**Comment by fpistm** [comment]
Yes, because JSON files has been updated,  you probably have 2 directories in Arduino local user folders.
If you change the "Additional Boards Managers URLs" to point on the previous one, it probably told that the 2018.1.18 is installed.
Please follow the Wiki to remove this old one because Arduino is not able to deal properly with that.

**Comment by sstaub** [comment]
Thank you, I found doubled files in the local user folders, now it works.
