### ISSUE TITLE
HardwareTimer stuck when using refresh()

### ISSUE THREAD

**Issue by stas2z** [stm32duino/Arduino_Core_STM32#617]
Using latest git snapshot to test hardware timer (trying to port SoftSerialIntAP to this core)
When i try to use resfresh() before resume() timers never start.

It's easy to reproduce it using timebase_callback example provided, just add refresh before resume in it
https://github.com/stm32duino/STM32Examples/blob/master/examples/Peripherals/HardwareTimer/Timebase_callback/Timebase_callback.ino

 - OS: linux 4.x
 - Arduino IDE version: 1.8.9
 - STM32 core version: 1.7.0 git
 - Upload method: STLink
 - Name: Nucleo 64 F103RE (RB chip burned, replaced with RE and added new variant for it)

**Comment by fpistm** [comment]
Hi @stas2z ,
Thanks for reporting.
we will investigate this. Mainly  @ABOSTM our expert 💪 😉

**Comment by ABOSTM** [comment]
Hi @stas2z ,
In fact it is not possible to call refresh() before the fisrt call to resume() because timer (the hardware registers) will not be yet initialized.
And there is no reason to do so: refresh() is usefull only while timer is running, in case you modify some parameters like capture/compare to make sure value is taken into account immediately, otherwise value is taken into account at next update event (timer rollover).
So as a general rule call refresh() only after resume(). I will add a comment about that in source code.
