### ISSUE TITLE
analogRead() slow on STM32F405

### ISSUE THREAD

**Issue by manitou48** [stm32duino/Arduino_Core_STM32#782]
on STM32F405, analogRead() takes 50 us.  On many other MCU's, analogRead() takes 5 us.

The datasheet says ADC stabilization time is 3 us, but in HAL_ADC_Start() in 
system/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
the while/counter stabilization delay is taking 37 us??

maybe a better delay loop would be

**while(counter--) asm("nop");**   

that loop takes about 3 cycles per iteration

**Comment by fpistm** [comment]
Hi @manitou48 
the analogRead is know to not be optimized as we it init, calibrate, start, wait conversion and stop each time it is called.
That's why there is an #5 to produce a better ADC usage.

About the HAL, the core use it as it is. I guess you could submit an issue here to talk about:
https://github.com/STMicroelectronics/STM32CubeF4
